### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ghost** [John-Paul-R/Essential-Commands#1]
Hi,
I was just wondering if this works for 1.16.5 and whether the commands are op level 4 only or able to be set to that?

**Comment by John-Paul-R** [comment]
Oops, I somehow did get/see a notification for this issue being created. Afaik, the code as of commit caea75bf18db2af586ed3e5e0b985bed6010583d should work with 1.16.5.

The current latest release works with 1.17 and has not been tested on 1.16.5.

ATM, the commands can be used by anyone. In the future, I may integrate with permissions managers instead.
