### ISSUE TITLE
Colors not parsed in motd [1.19]

### ISSUE THREAD

**Issue by BrightSteel** [John-Paul-R/Essential-Commands#103]
<img width="837" alt="Screen Shot 2022-06-18 at 6 11 11 PM" src="https://user-images.githubusercontent.com/11802079/174459767-beb6ca97-fcd2-4cc9-8f79-539926dfb9e5.png">

See above image; I think this is only a bug in the 1.19 dev release.

**Comment by John-Paul-R** [comment]
Thanks for the report! Will be fixed in next release (or now, in the artifacts from github "Actions" tab if you're comfortable with a dev build)

**Comment by John-Paul-R** [comment]
Fix made it into [`v0.24.1-mc1.19`](https://github.com/John-Paul-R/Essential-Commands/releases).

**Comment by the-n1n** [comment]
This has resurfaced on 1.18.2 V0.33.2
