### ISSUE TITLE
[suggestion] Replace vanilla /gamemode

### ISSUE THREAD

**Issue by BrightSteel** [John-Paul-R/Essential-Commands#104]
Hi, I'm wondering if you could replace the /gamemode command with a permission-based /gamemode and /gm. This way a users can access the command via a permission node as opposed to needing to be OP, and the alias is nifty as well.

**Comment by John-Paul-R** [comment]
For permissions on vanilla commands, I highly recommend you check out [Minecraft Command Permissions Fabric](https://github.com/lucko/minecraft-command-permissions-fabric)

For making aliases, [Command Aliases](https://github.com/FlashyReese/CommandAliases) is pretty comprehensive.

---

Broadly, I'm not trying to remake/restructure/modify vanilla commands in this particular mod.
