### ISSUE TITLE
Language issues

### ISSUE THREAD

**Issue by Leo204-LKY** [John-Paul-R/Essential-Commands#108]
If a text does not have a identifier in language file, it will only show its identifier.  
![image](https://user-images.githubusercontent.com/57821066/177348808-349a5752-a9d5-4a3d-8068-c44248b4045b.png)
Missing identifier can be shown in English as default.  

Besides, some text will only shown in English even it has a translation in `.lang` file.  
![image](https://user-images.githubusercontent.com/57821066/177347513-6421ec45-9f4d-4cea-952e-a9c765b92dc6.png)

**Comment by John-Paul-R** [comment]
Resolved by #107

**Comment by YanWQ-monad** [comment]
> Resolved by #107

I think the PR probably won't resolve the issue, because this sentence is hardcoded in the code.

https://github.com/John-Paul-R/Essential-Commands/blob/595a3403bb2130182f5287f23e83d07993660b0c/src/main/java/com/fibermc/essentialcommands/commands/TeleportAskCommand.java#L60-L63

**Comment by John-Paul-R** [comment]
Oh, quite true. Good catch, thanks
