### ISSUE TITLE
Suggestion: Remove the extra tp part from teleport-commands

### ISSUE THREAD

**Issue by Krimsar** [John-Paul-R/Essential-Commands#110]
It would be helpful if for example `/home <name>` would already initiate the teleport (or warp) and one could omit the redundant tp-part from the commands. 
Another useful addition would be the ability to have a home without a name, a main home if you will, and be able to teleport to it using `/home` only.

**Comment by John-Paul-R** [comment]
Thanks for the suggestion. This is a common request, just is a bit of a lift, (and can be emulated by making `CommandAliases` shortcuts)

> It would be helpful if for example /home <name> would already initiate the teleport (or warp) and one could omit the redundant tp-part from the commands.

This will be tracked by #50 

> Another useful addition would be the ability to have a home without a name, a main home if you will, and be able to teleport to it using /home only.

and this by #62

---

Consider it on the todo, though, just no ETA atm

**Comment by John-Paul-R** [comment]
(Oh, and in case it wasn't clear, the reason the `tp` argument is there to begin with is that the other subcommands would conflict with that arg if it was the "home name" param, thus the need for restructure mentioned in that first issue)
