### ISSUE TITLE
Update checker does not correctly account for MC version in semver.

### ISSUE THREAD

**Issue by John-Paul-R** [John-Paul-R/Essential-Commands#12]
Ideally, 1.17 vers existing should not affect whether a 1.16 vers is considered up-to-date.
Solution: different endpoints for different game versions?

**Comment by JohLenn** [comment]
Not sure I understand the fix correctly, but I shouldn't get an update notification, if I'm running the latest version of Essential-Commands for a given Minecraft version, right? I'm currently running MC 1.21.1 with EC 0.35.2 and yet my server log shows the following update notification:
A new version of Essential Commands is available. Current: '0.35.2-mc1.21' Latest: '0.38.5-mc1.21.8'. Get the new version at https://modrinth.com/mod/essential-commands

Modrinth tells me, that 0.35.2 is the latest EC version for 1.21.1 so I shouldn't get this message.

**Comment by John-Paul-R** [comment]
This should be resolved with the following series of commits in v0.40.0-beta1:

f621e52, 19e1569, c483cc7
