### ISSUE TITLE
Unable to rtp, Spawn not set.

### ISSUE THREAD

**Issue by notAreYouScared** [John-Paul-R/Essential-Commands#122]
Trying to use /rtp returns the following error

"Could not execute command  '/rtp' Reason: Spawn not set (RTP chooses a random location a preset distance from spawn.)"

I've set the spawn with '/setworldspawn', but still get the spawn not set error...

Edit:  Using [0.24.5-mc1.18.2](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.24.5-mc1.18.2), with All of Fabric 5 - 1.3.1 MCv1.18.2

**Comment by John-Paul-R** [comment]
You'll need to set the Essential Commands spawn point with `/spawn set`
