### ISSUE TITLE
Teleporting through dimensions takes away all experience.

### ISSUE THREAD

**Issue by AchalS-iglu** [John-Paul-R/Essential-Commands#128]
Home teleporting through dimensions takes away all experience.
essential_commands-0.26.1-mc1.19.jar

**Comment by John-Paul-R** [comment]
Does the exp come back if you relog? If so, this sounds like [MC-132543](https://bugs.mojang.com/browse/MC-132543).

If so, there are actually some fabric mods that attempt to resolve that bug:
- https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug

**Comment by AchalS-iglu** [comment]
> Does the exp come back if you relog? If so, this sounds like [MC-132543](https://bugs.mojang.com/browse/MC-132543).
> 
> If so, there are actually some fabric mods that attempt to resolve that bug:
> 
>     * https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug

OH yeah it is the same thing!!! thank you I will use this mod!
