### ISSUE TITLE
Get rid of having to do /home tp (name), so its just /home (name)?

### ISSUE THREAD

**Issue by John-Paul-R** [John-Paul-R/Essential-Commands#13]
> One more question, is there a way to get rid of having to do /home tp (name), so its just /home (name)? It's nothing big but very curious.

[Original suggestion](https://www.curseforge.com/minecraft/mc-mods/essential-commands?comment=15) (CurseForge)

**Comment by MattElekHarris** [comment]
The same thing would be great for /tpaccept and /tpadeny, if there's only one pending tpa request. Also for /home, if only one home exists.

**Comment by John-Paul-R** [comment]
This is actually a great idea. Thanks for suggesting it. Will definitely add these shortcuts for when only one valid value exists for a command argument.

**Comment by John-Paul-R** [comment]
Moved "command shortcuts" suggestion to #51.

This issue's original suggestion is now a duplicate of #50, and will be tracked there.
