### ISSUE TITLE
Remove Co-ordinate message on Home TP

### ISSUE THREAD

**Issue by Blitzgott1309** [John-Paul-R/Essential-Commands#131]
Is there a way on config to disable the coordinates appearing in chat when you teleport to a home? This is really awkward when streaming on discord or twitch as to keep a base secret, you must manually disable chat which brings a whole host of new issues. Thanks for any responses!

**Comment by John-Paul-R** [comment]
Heh, I see how that could be problematic. Will look into adding an option for this.

**Comment by Blitzgott1309** [comment]
Thanks for sorting this so quick! You’re amazing!

**Comment by John-Paul-R** [comment]
Just released in [0.27.0-beta-mc1.19](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.27.0-beta-mc1.19). Instructions on how to use are in the release notes.

This release does have quite a lot in it, and I'm still testing some of it, so some bugs may have slipped through at this stage.

In my testing, though, the profile option for hiding coordinates in chat feedback works just fine. Hope you enjoy!
