### ISSUE TITLE
/anvil command doesnt exist in 1.19

### ISSUE THREAD

**Issue by sauramel** [John-Paul-R/Essential-Commands#140]
Thats just it, can find the /anvil command, nor does the permission essentialcommands.anvil exist

**Comment by John-Paul-R** [comment]
Can you send your `config/EssentialCommands.properties` file? Also, what version of EC are you using, specifically?

**Comment by sauramel** [comment]
Hey, I was in the process of grabbing the .properties and have found that the enable_anvil setting is false by default. Thanks!
