### ISSUE TITLE
Teleport to spawn after death

### ISSUE THREAD

**Issue by stanlystark** [John-Paul-R/Essential-Commands#142]
How can I make a teleport to spawn point after death if the player does not have a bed?

**Comment by John-Paul-R** [comment]
Seems reasonable. Will add in an upcoming release.

In the interim, you might find `/setworldspawn` useful.

**Comment by stanlystark** [comment]
> Seems reasonable. Will add in an upcoming release.

that would be wonderful

> In the interim, you might find `/setworldspawn` useful.

the problem is that the server's rebirth point is needed in another world (for example, in nether or another modded world)

**Comment by John-Paul-R** [comment]
Wow, I completely lost track of this, my bad. Added in [cfc0ba2](https://github.com/John-Paul-R/Essential-Commands/commit/cfc0ba2858fa2193f2bfc33b71a81084eac6dbd2). Will be in the next release, which I intend to publish this weekend.

**Comment by John-Paul-R** [comment]
Released in [0.29.0-mc1.19.2](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.29.0-mc1.19.2)
