### ISSUE TITLE
Add `/rules` command

### ISSUE THREAD

**Issue by TecEash1** [John-Paul-R/Essential-Commands#145]
On the default motd it says something about us reading our rules, how to players do that - is there a command or smth?

**Comment by John-Paul-R** [comment]
That's... a great question lol. No, there is no `/rules` atm. I'll add that w/in the week. Seems useful.

(I'd sort of just assumed people would have signs or something, but you raise a good point. Is strange that I mention rules, but don't provide a way to view them haha)

TODO `@me`: if you do this, make sure chars from other languages do not get mangled like with `EssentialCommands.properties`

**Comment by TecEash1** [comment]
Thanks 👍

**Comment by John-Paul-R** [comment]
Added in 99f2198c5357ce4e5e02f7594c4130e781e38972. Will be in the next release (0.30.0).
