### ISSUE TITLE
[Feature] Disable config date update when there are no changes

### ISSUE THREAD

**Issue by ChristopherHaws** [John-Paul-R/Essential-Commands#153]
Hi there! I like to keep my config files in a private git repo since it helps me keep track of the changes and easily revert them if needed. This is one of a few mods that updates the date/time at the top of the file every time the server is restarted. Would it be possible to change this behavior to only change if values in the config file are being updated by the mod?

![image](https://user-images.githubusercontent.com/5934505/204050290-3dfb2b75-d959-490c-8016-88e6f87845be.png)

Thanks! :)

**Comment by John-Paul-R** [comment]
yep, easy enough to do. Will change this for the next release.
