### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by disymayufei** [John-Paul-R/Essential-Commands#158]
[Server] [23:32:54] [Server thread/ERROR]: Encountered an unexpected exception
[Server] java.lang.NoSuchFieldError: field_11735
[Server]        at com.fibermc.essentialcommands.playerdata.PlayerData.setAfk(PlayerData.java:225) ~[essential_commands-0.30.0-mc1.19.jar:?]
[Server]        at com.fibermc.essentialcommands.playerdata.PlayerData.onTickEnd(PlayerData.java:273) ~[essential_commands-0.30.0-mc1.19.jar:?]
[Server]        at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4780) ~[?:?]
[Server]        at com.fibermc.essentialcommands.playerdata.PlayerDataManager.tick(PlayerDataManager.java:122) ~[essential_commands-0.30.0-mc1.19.jar:?]
[Server]        at com.fibermc.essentialcommands.playerdata.PlayerDataManager.lambda$init$0(PlayerDataManager.java:54) ~[essential_commands-0.30.0-mc1.19.jar:?]
[Server]        at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:62) ~[fabric-lifecycle-events-v1-2.1.2+aeb40ebe90-3d9d1db039208512.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$bpj000$onEndTick(MinecraftServer.java:7321) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.handler$zbf000$modifiedRunLoop(MinecraftServer.java:2885) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[server-intermediary.jar:?]
[Server]        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
[Server]        at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by John-Paul-R** [comment]
What version of Minecraft are you running? If you're running 1.19.2 or higher, make sure your essential commands version matches.

**Comment by disymayufei** [comment]
My Minecraft version is 1.19.2，and I'm sure that I use the correct version of essential commands

**Comment by John-Paul-R** [comment]
Hmm.. Based on these logs, Your installed EC version looks to be for 1.19, not 1.19.2. (the version here is `essential_commands-0.30.0-mc1.19.jar` I'd expect [`essential_commands-0.30.0-mc1.19.2.jar`](https://github.com/John-Paul-R/Essential-Commands/releases/download/0.30.0-mc1.19.2/essential_commands-0.30.0-mc1.19.2.jar) if it were the 1.19.2 version.)

**Comment by disymayufei** [comment]
That's because I fork your 1.19 branch and compile it by own

**Comment by disymayufei** [comment]
solved, thanks!
