### ISSUE TITLE
Feature: Players can use the `/home tp bed` to teleport to their own bed.

### ISSUE THREAD

**Issue by LittleCircleOO** [John-Paul-R/Essential-Commands#159]
Just like the Essential plugin's behavior, players can return to their spawn point via the `/home tp bed` command.
Or rather, the mod will automatically create a new `home` for the player's spawn point.

**Comment by John-Paul-R** [comment]
seems reasonable, will add a config option for displaying bed as a predefined home

**Comment by John-Paul-R** [comment]
actually, adding this as `/bed`, to avoid naming conflicts

**Comment by Silverteal** [comment]
Can we teleport to bed now?
