### ISSUE TITLE
Losing xp when teleporting (video included)

### ISSUE THREAD

**Issue by HIHIE-YT** [John-Paul-R/Essential-Commands#161]
Video showing the bug -> https://youtu.be/-xNa2SkBkXo

This happens to everyone on the server and with all the tp commands (not just /warp)

Love this mod, use it all the time on my servers just saw a small bug and was wondering if its something I'm doing wrong or if its the mod itself. The server is a fabric server and it has a couple other mods but I don't think that would affect anything.

**Comment by John-Paul-R** [comment]
Hi there! Thanks for the report. I think this is actually an MC bug. Lmk if this solves your problem: https://github.com/John-Paul-R/Essential-Commands/issues/128#issuecomment-1193314044

**Comment by HIHIE-YT** [comment]
> Hi there! Thanks for the report. I think this is actually an MC bug. Lmk if this solves your problem: [#128 (comment)](https://github.com/John-Paul-R/Essential-Commands/issues/128#issuecomment-1193314044)

This worked!!! thanks so much. this mod is definitely my favorite mod I have on my server!! (also my friend says he loves you)
