### ISSUE TITLE
[Suggestion] Add /vanish command

### ISSUE THREAD

**Issue by Sebas-Re** [John-Paul-R/Essential-Commands#166]
Hey there!
I think it would be a nice addition to this mod to be able to /vanish and hide from other players (for moderation purposes), and (not sure if it would be possible tho) integrate it with discord bridge mods like Discordium https://github.com/FederAndInk/Discordium

**Comment by John-Paul-R** [comment]
Hiya! I recommend checking out these vanish mods to see if they do what you're looking for:

- https://github.com/DrexHD/Vanish
- https://github.com/123456687548/vanish

**Comment by Sebas-Re** [comment]
Oooohhhh I'll check them out, many thanks!!

**Comment by John-Paul-R** [comment]
gotchu!
