### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.lines()" because "propsContent" is null

### ISSUE THREAD

**Issue by disymayufei** [John-Paul-R/Essential-Commands#167]
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'essential_commands'!
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.12.jar:?]
[Server]        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
[Server]        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.12.jar:?]
[Server]        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server-1.19.2.jar:0.11.1]
[Server] Caused by: java.lang.NullPointerException: Cannot invoke "String.lines()" because "propsContent" is null
[Server]        at dev.jpcode.eccore.config.Config.getNonCommentsLines(Config.java:34) ~[ec-core-1.3.0-mc1.19.2-b17869ce8e5e6ad8.jar:?]
[Server]        at dev.jpcode.eccore.config.Config.storeProperties(Config.java:93) ~[ec-core-1.3.0-mc1.19.2-b17869ce8e5e6ad8.jar:?]
[Server]        at dev.jpcode.eccore.config.Config.loadOrCreateProperties(Config.java:65) ~[ec-core-1.3.0-mc1.19.2-b17869ce8e5e6ad8.jar:?]
[Server]        at com.fibermc.essentialcommands.EssentialCommands.onInitialize(EssentialCommands.java:61) ~[essential_commands-0.30.0-mc1.19.2.jar:?]
[Server]        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.12.jar:?]

**Comment by disymayufei** [comment]
Note: this bug will only occur when the config file doesn't exist.

**Comment by John-Paul-R** [comment]
yep, good call. should be fixed by 27388a266ce181f08730c72d5cf5a5b94cbda621

Will be included in next patch release
