### ISSUE TITLE
0.31.0 for Fabric 1.18.2

### ISSUE THREAD

**Issue by SilianZ** [John-Paul-R/Essential-Commands#175]
I really need this version.
Please

**Comment by John-Paul-R** [comment]
here ya go: [Release 0.31.1-mc1.18.2](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.31.1-mc1.18.2)

Enjoy!

**Comment by John-Paul-R** [comment]
(this is the first proper 1.18 backport in a while, so there may be new bugs. Feel free to report them as they appear.)
