### ISSUE TITLE
crash server Fabric 1.19.2

### ISSUE THREAD

**Issue by MrJorman** [John-Paul-R/Essential-Commands#179]
[crash-2023-02-13_14.28.33-server.txt](https://github.com/John-Paul-R/Essential-Commands/files/10721729/crash-2023-02-13_14.28.33-server.txt)

**Comment by John-Paul-R** [comment]
I believe this is a bug I fixed in `0.30.2-mc1.19.3`. I'll backport this fix to 1.19.2 later today.

**Comment by MrJorman** [comment]
thank

**Comment by John-Paul-R** [comment]
Oop, forgot I had something scheduled for this evening. I'll come back to this tomorrow.

Also, to confirm, this doesn't happen every time you start the server, right? It's a rare issue? (or am I incorrect in that assumption?)

**Comment by MrJorman** [comment]
> Oop, forgot I had something scheduled for this evening. I'll come back to this tomorrow.
> 
> Also, to confirm, this doesn't happen every time you start the server, right? It's a rare issue? (or am I incorrect in that assumption?)

rare issue

**Comment by MrJorman** [comment]
But it still needs to be fixed!

**Comment by John-Paul-R** [comment]
> But it still needs to be fixed!

Yep, ofc. Just confirming it's the issue I'm thinking of.

**Comment by John-Paul-R** [comment]
Here, this is a fix for 1.19.2: https://drive.google.com/file/d/1efh05SKtOB-iXkeLiXDwy7M6-7ciIpNv/view?usp=share_link
