### ISSUE TITLE
Command abbreviation /home /sethome

### ISSUE THREAD

**Issue by MrJorman** [John-Paul-R/Essential-Commands#180]
Is it possible to add alias to the command somehow

/sethome /home set - To create a house with the name home and if you register it again, then the point of the house was overwritten. And also after death, I appeared at the point of the house, and not at the bed.
/home - To just teleport home without the /home tp command

**Comment by MrJorman** [comment]
It's just that players are always confused in the commands /home set {name} or /home tp {name} it's easier to shorten the abbreviation

**Comment by MrJorman** [comment]
How is this done in normal plug-ins like Essentials or CMI

**Comment by John-Paul-R** [comment]
Hi! Please see the pinned issue (https://github.com/John-Paul-R/Essential-Commands/issues/50#issuecomment-1198257413)
