### ISSUE TITLE
Add invsee

### ISSUE THREAD

**Issue by ItsaGlitch1** [John-Paul-R/Essential-Commands#185]
add the ability for ops or players with a specific permission to view other player's inventories and enderchests.
Also, add another permission or let ops edit other player's inventory/echest

**Comment by John-Paul-R** [comment]
I highly recommend [InvView](https://github.com/PotatoPresident/InvView) for this for this type of thing.

As a general rule, I do not add features to EC if another, more specific mod already implements the feature well.

---

Related, potentially useful:

  - [Mods I recommend](https://github.com/John-Paul-R/Essential-Commands/wiki/Recommended-Companion-Mods)
  - [Quilt Server-side Mods](https://serverside.infra.link/) (Most, if not all work with Fabric)
