### ISSUE TITLE
/motd command does not exist

### ISSUE THREAD

**Issue by unilock** [John-Paul-R/Essential-Commands#188]
Sometimes the MOTD doesn't appear on player join, nor does the server show `/motd` as a valid command.

I can't figure out how to reliably reproduce this... I think disabling all commands / features except `enable_motd` has made it more likely to happen in the past, but I'm not 100% certain.

Deleting and regenerating the config file and/or world has no effect, as far as I can tell.

Minecraft: `1.19.3`
Fabric loader: `0.14.14`
Essential Commands: `0.31.1`
Fabric API: `0.75.1`

If I recall correctly, I had the exact same config working reliably with Essential Commands v0.30.0 on 1.19.2.

**Comment by John-Paul-R** [comment]
Hmm, I'm struggling to reproduce. Can you provide your `logs/latest.log` (e.g. https://mclo.gs/) and `config/EssentialCommands.properties`?

**Comment by unilock** [comment]
Sorry for the late response!

[EssentialCommands.properties](https://gist.github.com/unilock/dc05c410cf5b81669375a5416af6881a#file-essentialcommands-properties)
[latest.log](https://gist.github.com/unilock/dc05c410cf5b81669375a5416af6881a#file-latest-log)

Now testing with:
- Minecraft: `1.19.3`
- Fabric loader: `0.14.17`
- Essential Commands: `0.31.1`
- Fabric API: `0.76.0`

**Comment by unilock** [comment]
This appears to have been fixed in 0.32.0 :)
But I can't pinpoint which commit fixed it...

In reference to that - is this issue ready to be closed?

**Comment by John-Paul-R** [comment]
> This appears to have been fixed in 0.32.0 :)
But I can't pinpoint which commit fixed it...

Lol, well that makes two of us. I was at a dead end with reproducing this. If you're not experiencing the issue anymore, yes, feel free to close! (Thanks for the update)

**Comment by unilock** [comment]
Sorry for the late response; I was doing a bit more testing (and got distracted) :)

It looks like the MOTD consistently appears every time I log into the server! But, `/motd` still isn't a valid command!?

> Lol, well that makes two of us.

I assumed this was the fix:

<img width="742" alt="image" src="https://user-images.githubusercontent.com/11802133/226585242-beb92ce0-d237-4bb2-94cf-0e1a14d48779.png">

But I couldn't figure out which commit correlated with that?

**Comment by John-Paul-R** [comment]
Aha, good call, that's almost certainly it. This is the commit: https://github.com/John-Paul-R/Essential-Commands/commit/62b1ca1e9f57230f36b51caef701755998495ecb

And... I think I mind controlled myself into thinking that I added `/motd` as a command. I don't see that in the code. I'll add that in the next release!
