### ISSUE TITLE
/nickname command not registering

### ISSUE THREAD

**Issue by bumpyJake** [John-Paul-R/Essential-Commands#192]
I am currently having an issue where any player that is not opped cannot use the /nickname command

It shows up as such - 
![image](https://user-images.githubusercontent.com/93681991/226071169-e2eccd49-085d-4f17-9dea-9673d58de7fb.png)

However the permission to use it is set
![image](https://user-images.githubusercontent.com/93681991/226071194-777b57e3-a229-4b21-9cce-78e2cf63a92a.png)

**Comment by John-Paul-R** [comment]
Hm. I've not seen this before.

Can you provide the contents of your `config/EssentialCommands.properties` and a https://mclo.gs/ (or equivalent) of your `logs/latest.log`?

**Comment by bumpyJake** [comment]
The logs just say
[17:30:56] [Render thread/INFO]: [System] [CHAT] Unknown or incomplete command, see below for error
[17:30:56] [Render thread/INFO]: [System] [CHAT] nickname test<--[HERE]

heres the config https://mclo.gs/h7A7ZUe

**Comment by unilock** [comment]
You have `use_permissions_api` set to `false` in your Essential Commands config. Changing it to `true` will likely solve the issue ;)

**Comment by bumpyJake** [comment]
This was the case! Thank you
