### ISSUE TITLE
Crash with Tweakeroo

### ISSUE THREAD

**Issue by XImaPlayerX** [John-Paul-R/Essential-Commands#21]
Reproduce: Bind key to Freecam tweak, press keybind, crash.

[crash-2021-06-30_14.04.09-client.txt](https://github.com/John-Paul-R/Essential-Commands/files/6740734/crash-2021-06-30_14.04.09-client.txt)

**Comment by John-Paul-R** [comment]
What version of Essential Commands are you using? There was a fix in v0.7.3 that might resolve this issue.

**Comment by John-Paul-R** [comment]
Going to assume this issue has been fixed. Feel free to comment on this issue if you are still encountering the same problem.

**Comment by XImaPlayerX** [comment]
Didn't realize it was outdated, sorry about that, I'm usually good at keeping mods updated but must've missed this one.

Sadly, it does not seem to have been fixed. I tried running both 0.7.3, and 0.8.0, but the crash still occurs.
Here are the crash reports for both versions:
0.8.0 - [crash-2021-07-03_06.25.05-client.txt](https://github.com/John-Paul-R/Essential-Commands/files/6757835/crash-2021-07-03_06.25.05-client.txt)
0.7.3 - [crash-2021-07-03_06.26.25-client.txt](https://github.com/John-Paul-R/Essential-Commands/files/6757836/crash-2021-07-03_06.26.25-client.txt)

**Comment by John-Paul-R** [comment]
Oh, this is a issue with running on the client, almost certainly.

Normally, when I test this mod, I test only for servers, because that is where it is intended to run. Because of this, it seems a bug slipped through the cracks.

Will attempt to fix in an upcoming release.

**Comment by John-Paul-R** [comment]
Latest commit fixes this issue. Should have a release with the changes sometime tomorrow.

**Comment by John-Paul-R** [comment]
Should be fixed in [release 0.9.1](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.9.1-beta-mc1.17)!

**Comment by XImaPlayerX** [comment]
Can confirm it has been fixed! Awesome job. :)
