### ISSUE TITLE
[Bug] `allow_back_on_death` feature seems to sometimes silently fail

### ISSUE THREAD

**Issue by John-Paul-R** [John-Paul-R/Essential-Commands#211]
source https://github.com/John-Paul-R/Essential-Commands/issues/99#issuecomment-1544454061

**Comment by RockZe** [comment]
https://github.com/John-Paul-R/Essential-Commands/issues/99#issuecomment-1545901332

After your comment, I decided to check it out on the new Minecraft client profile, which has no mods except _essential_commands-0.33.0-mc1.19.2.jar_ and _fabric-api-0.76.0+1.19.2.jar_. Version 1.19.2 with loader 0.14.18

Of course I made _allow_back_on_death=true_. But unfortunately, when trying to return to the place of death in the new world, I get an error. Given this, I'm still inclined to believe that it's not the incompatibility of mods, but most likely some kind of error of the /back command

![image](https://github.com/John-Paul-R/Essential-Commands/assets/123874691/8166f85b-4294-4b63-86c6-d2935e51fabb)

At the same time, if I teleport by command, or between home or warp, then the back command works fine!

**Comment by John-Paul-R** [comment]
Same issue happening on 1.19.4

https://discord.com/channels/513219024927326211/857077956336943154/1113859028066504825

**Comment by John-Paul-R** [comment]
have a reported working configuration with

```
MC 1.19.2
Fabric Loader 0.14.19
fabric-api 0.76.0+1.19.2
EC 0.33.0
```

https://discord.com/channels/513219024927326211/857077956336943154/1113871422536810640

**Comment by John-Paul-R** [comment]
People I need to ping when I fix this:

```
535613178655145984
799216016080240640
1077257387934756975
```

**Comment by John-Paul-R** [comment]
Another repro:
https://mclo.gs/h6cS1Aa

**Comment by John-Paul-R** [comment]
@arnokeesman correctly identified the root cause of the bug. (Thanks again!)

The logic for keeping `PlayerData` in-sync was early-out-ing if a World Spawn was not set (IOW running `/spawn set` is a temporary workaround).

I'll be looking to release a version with a fix today.
