### ISSUE TITLE
The "/back" command does not work on death but works otherwise

### ISSUE THREAD

**Issue by Lafatalite** [John-Paul-R/Essential-Commands#213]
The "/back" command does not work on death but works otherwise. "allow_back_on_death" is also enabled and I only installed this mod in 1.19.2
It says "Could not execute 'back' command, No previous location found, "and when I use '/back' after my death, But I used "/back" in the "/home" setting and the config I only changed" allow_back_on_death"
I also found this problem in 1.19.4
[issue_back_20230606.zip](https://github.com/John-Paul-R/Essential-Commands/files/11654962/issue_back_20230606.zip)

**Comment by Lafatalite** [comment]
![Uploading mods.png…]()

**Comment by John-Paul-R** [comment]
Closing in favor of ~~#213~~ #211
