### ISSUE TITLE
EXP vanishing for no reason (singleplayer)

### ISSUE THREAD

**Issue by GRRbew** [John-Paul-R/Essential-Commands#226]
ok so i finishe building my enderman farm and i used it for a while and got to level 30 so then i /home tp away from the enderman farm to go to apply mending on my items but i couldnt because my EXP was gone it was drained to 0 so i went back to the farm again and my exp still didnt appear so i killed a few endermen and finally my exp showed up but then i warped away and lost my exp again it doesnt matter how many times i try the exp will vanish once i tp away.

**Comment by John-Paul-R** [comment]
I think this is an MC bug. Lmk if this solves your problem: https://github.com/John-Paul-R/Essential-Commands/issues/128#issuecomment-1193314044

**Comment by GRRbew** [comment]
thank you
