### ISSUE TITLE
Server crashes randomly on a player join

### ISSUE THREAD

**Issue by AchalS-iglu** [John-Paul-R/Essential-Commands#227]
Server crashes randomly on a player join

`---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2023-06-30 21:44:38
Description: Exception in server tick loop

java.lang.NullPointerException: Cannot read field "next" because "this.next" is null
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:897)
	at com.fibermc.essentialcommands.playerdata.PlayerDataManager.tick(PlayerDataManager.java:132)
	at com.fibermc.essentialcommands.playerdata.PlayerDataManager.lambda$init$0(PlayerDataManager.java:59)
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
	at net.minecraft.server.MinecraftServer.handler$zfj000$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:3362)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.10.0-21-amd64
	Java Version: 17.0.7, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 2545320624 bytes (2427 MiB) / 4294967296 bytes (4096 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 2
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 105296.58
	Virtual memory used (MB): 142414.16
	Swap memory total (MB): 40927.00
	Swap memory used (MB): 22460.33
	JVM Flags: 2 total; -Xms128M -Xmx4096M
	Fabric Mods: 
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		colorfulanvils: Colorful Anvils 1.2.0+1.20.x
			fabric-api-base: Fabric API Base 0.4.29+b04edc7a77
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.1.1+1.20
		craterlib: CraterLib 1.0.1
		deathlog: DeathLog 0.3.2+1.20
		easyauth: Easy Authentication Mod 3.0.0-17
			at_favre_lib_bcrypt: bcrypt 0.9.0
			at_favre_lib_bytes: bytes 1.5.0
			com_mysql_mysql-connector-j: mysql-connector-j 8.0.33
			de_mkammerer_argon2-jvm: argon2-jvm 2.11
			de_mkammerer_argon2-jvm-nolibs: argon2-jvm-nolibs 2.11
			net_java_dev_jna_jna: jna 5.12.1
			org_iq80_leveldb_leveldb: leveldb 0.12
			org_iq80_leveldb_leveldb-api: leveldb-api 0.12
			org_mongodb_bson: bson 4.7.2
			org_mongodb_mongodb-driver-core: mongodb-driver-core 4.7.2
			org_mongodb_mongodb-driver-sync: mongodb-driver-sync 4.7.2
			server_translations_api: Server Translations API 2.0.0+1.20
				packet_tweaker: Packet Tweaker 0.4.0+1.19.4
		essential_commands: Essential Commands 0.33.2-mc1.20
			ec-core: Essential Commands Core 1.3.0-mc1.20
			playerabilitylib: Pal 1.8.0
		fabric-api: Fabric API 0.84.0+1.20.1
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.34+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.10+b3afc78b77
			fabric-block-api-v1: Fabric Block API (v1) 1.0.9+e022e5d177
			fabric-command-api-v1: Fabric Command API (v1) 1.2.32+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.11+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.49+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.61+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.7+b3afc78b77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.3+b3afc78b77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.1.11+b3afc78b77
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.51+b3afc78b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.21+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.0+b3afc78b77
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.61+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.38+b04edc7a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.26+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.7+b3afc78b77
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.20+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.37+b3afc78b77
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.41+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.6+b3afc78b77
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.47+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.8+b3afc78b77
			fabric-networking-v0: Fabric Networking (v0) 0.3.48+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.0.6+b3afc78b77
			fabric-particles-v1: Fabric Particles (v1) 1.0.28+b3afc78b77
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.18+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.2.6+b3afc78b77
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.33+b3afc78b77
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.26+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.5+ea08f9d877
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.7+f7923f6d77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.27+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.2.2+b3afc78b77
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.2.0+b3afc78b77
		fabric-language-kotlin: Fabric Language Kotlin 1.9.6+kotlin.1.8.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.21.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.1
		fabricloader: Fabric Loader 0.14.21
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
		ferritecore: FerriteCore 6.0.0
		goml: Get Off My Lawn ReServed 1.9.0+1.20-rc1
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
			polymer-core: Polymer (Core) 0.5.0-rc.2+1.20-rc1
				polymer-networking: Polymer (Networking) 0.5.0-rc.2+1.20-rc1
					polymer-common: Polymer (Common) 0.5.0-rc.2+1.20-rc1
			rtree-3i-lite-fabric: rtree-3i-lite for Fabric 0.3.0
			sgui: sgui 1.2.2+1.20
		horsebuff: HorseBuff 2.1.1
			cloth-config: Cloth Config v11 11.0.99
				cloth-basic-math: cloth-basic-math 0.6.1
		htm: Hey That's Mine 1.1.9
			common-protection-api: Common Protection API 1.0.0
		inventorysorter: Inventory Sorter 1.9.0-1.20
			kyrptconfig: Kyrpt Config 1.5.6-1.20
		itemflexer: ItemFlexer 1.3.0
			microconfig: Microconfig 2.2.1
		java: OpenJDK 64-Bit Server VM 17
		keepheadnames: Keep Head Names 1.5.1
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		ledger: Ledger 1.2.8
		lithium: Lithium 0.11.2
		mclogs: Mclogs 1.4.1
			gs_mclo_api: api 4.0.1
		memoryleakfix: Memory Leak Fix 1.1.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.8
		minecraft: Minecraft 1.20.1
		mixintrace: MixinTrace 1.1.1+1.17
		mods-command: Mods Command 1.1.3
			adventure-platform-fabric: adventure-platform-fabric 5.10.0-SNAPSHOT
				net_kyori_adventure-api: adventure-api 4.14.0
				net_kyori_adventure-key: adventure-key 4.14.0
				net_kyori_adventure-platform-api: adventure-platform-api 4.3.0
				net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.14.0
				net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.14.0
				net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.14.0
				net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.14.0
				net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.14.0
				net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.14.0
				net_kyori_ansi: ansi 1.0.0
				net_kyori_examination-api: examination-api 1.3.0
				net_kyori_examination-string: examination-string 1.3.0
			cloud: Cloud 1.8.3
				cloud_commandframework_cloud-brigadier_: cloud-brigadier 1.8.3
				cloud_commandframework_cloud-core_: cloud-core 1.8.3
				cloud_commandframework_cloud-services_: cloud-services 1.8.3
			cloud_commandframework_cloud-minecraft-extras: cloud-minecraft-extras 1.8.3
			com_typesafe_config: config 1.4.2
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
			org_spongepowered_configurate-yaml: configurate-yaml 4.1.2
			org_yaml_snakeyaml: snakeyaml 1.34-SNAPSHOT
		multiworldborders: Multi World Borders 1.6.1-fabric-1.20
		nochatreports: No Chat Reports 1.20.1-v2.2.2
		owo: oωo 0.11.0+1.20
			blue_endless_jankson: jankson 1.2.2
		pingspam: Pingspam 1.3.1+1.20
			onedatastore: One Data Store 0.1.3+1.20
		plan: Plan 5.5 build 2411
		sdlink: Simple Discord Link 2.2.2
		spark: spark 1.10.42
		starlight: Starlight 1.1.2+fabric.dbc156f
		styledchat: Styled Chat 2.2.0+1.20
		styledplayerlist: Styled Player List 3.1.1+1.20.1
			player-data-api: Player Data API 0.2.2+1.19.3
			predicate-api: Predicate API 0.1.2+1.20
		tabtps-fabric: TabTPS 1.3.18
			net_kyori_adventure-serializer-configurate4: adventure-serializer-configurate4 4.14.0
			net_kyori_adventure-text-feature-pagination: adventure-text-feature-pagination 4.0.0-SNAPSHOT
			net_kyori_adventure-text-serializer-legacy: adventure-text-serializer-legacy 4.14.0
		textile_backup: Textile Backup 3.1.0-1.20
			com_github_shevek_parallelgzip: parallelgzip af5f5c297e735f3f2df7aa4eb0e19a5810b8aff6
			org_apache_commons_commons-compress: commons-compress 1.22
			org_tukaani_xz: xz 1.9
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.3
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.0+1.20
		voicechat: Simple Voice Chat 1.20.1-2.4.12
	Server Running: true
	Player Count: 4 / 20; [class_3222['Stonebanks16'/192726, l='ServerLevel[world]', x=-318.28, y=65.00, z=236.96], class_3222['S_Sam312'/199849, l='ServerLevel[world]', x=8.06, y=73.00, z=331.28], class_3222['SirePoopAlot'/211602, l='ServerLevel[world]', x=-57.31, y=71.00, z=120.95], class_3222['iglushrek'/212339, l='ServerLevel[world]', x=194.96, y=76.54, z=814.95]]
	Data Packs: vanilla, fabric, file/afk display v1.1.4 (MC 1.20.x).zip, file/anti enderman grief v1.1.4 (MC 1.20.x).zip, file/armor statues v2.8.5 (MC 1.20.x).zip, file/double shulker shells v1.3.4 (MC 1.20.x).zip, file/more mob heads v2.12.1 (MC 1.20.x).zip, file/player head drops v1.1.4 (MC 1.20.x).zip, file/silence mobs v1.1.4 (MC 1.20.x).zip, file/track raw statistics v1.7.0 (MC 1.20.x).zip, file/track statistics v1.1.5 (MC 1.20.x).zip, file/unlock all recipes v2.0.5 (MC 1.20.x).zip, file/wandering trades hermit edition v1.8.1 (MC 1.20.x).zip, file/BlazeandCave's+Advancements+Pack+1.16.1.zip, file/fast leaf decay v2.0.7 (MC 1.20.x).zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)`

**Comment by John-Paul-R** [comment]
I'm not entirely sure how this is happening, but I just simplified this code path a tiny bit. Hoping that resolves the issue (264e86f). Will be included in the next patch release.

**Comment by AchalS-iglu** [comment]
> I'm not entirely sure how this is happening, but I just simplified this code path a tiny bit. Hoping that resolves the issue ([264e86f](https://github.com/John-Paul-R/Essential-Commands/commit/264e86ffe7097741b504391680a9c5e4fb939e78)). Will be included in the next patch release.

Hey, thank you! should I download the build file or wait for release?

**Comment by John-Paul-R** [comment]
Downloading the build from the GH Action artifacts should be good. Not sure when next release will be yet.

**Comment by AchalS-iglu** [comment]
Hey, your update fixed it! thanks!
