### ISSUE TITLE
Clickable Accept/Reject chat buttons for TPA requests. (optional)

### ISSUE THREAD

**Issue by Soham52** [John-Paul-R/Essential-Commands#23]
the TPA command can be improved even more by making it a bit like this

![Capture](https://user-images.githubusercontent.com/73898737/124244942-1bc02f80-db3d-11eb-872d-e85d7dda90af.PNG)

**Comment by John-Paul-R** [comment]
I like this idea. Thanks for suggesting it. Will definitely look into adding this at some point (no eta atm).
