### ISSUE TITLE
XP levels not shown after interdimensional /home tp

### ISSUE THREAD

**Issue by petersv5** [John-Paul-R/Essential-Commands#239]
When doing a /home tp or /back that crosses dimensions the XP levels show as empty on the client. As soon as any new XP is aquired the correct value is shown. Teleports within the dimesion leave the XP shown correctly.

This does prevent e.g. enchanting until the XP levels are updated. Is that check done client side as well as server side, or is there some out-of-sync on the server side as well?

MC 1.20.1
EssentialCommand 0.33.2-mc1.20

**Comment by John-Paul-R** [comment]
This sounds like [MC-132543](https://bugs.mojang.com/browse/MC-132543).

This fabric mod should resolve your problem:
- https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug

**Comment by John-Paul-R** [comment]
related, for my own sake:

- https://github.com/John-Paul-R/Essential-Commands/issues/64#issuecomment-908798010
- https://github.com/John-Paul-R/Essential-Commands/issues/128
- https://github.com/John-Paul-R/Essential-Commands/issues/161
- https://github.com/John-Paul-R/Essential-Commands/issues/226
- https://github.com/John-Paul-R/Essential-Commands/issues/191

**Comment by John-Paul-R** [comment]
> Is that check done client side as well as server side, or is there some out-of-sync on the server side as well?

I believe the button checks are done client-side, so if player state gets out of sync with the server (which I believe is what happens in this bug), you won't be able to enchant.

**Comment by petersv5** [comment]
Thank you.
We'll try that mod after the next planned restart.
