### ISSUE TITLE
Please adapt to 1.20.2

### ISSUE THREAD

**Issue by AomiRaku** [John-Paul-R/Essential-Commands#247]
Please adapt to 1.20.2！
It is known that "PlayerAbilityLib-1.8.0.jar" in mod cannot be loaded by 1.20.2.

**Comment by John-Paul-R** [comment]
resolved by #249 

dev jars available from "artifacts" here https://github.com/John-Paul-R/Essential-Commands/actions/runs/6283725411

will release new EC versions today
