### ISSUE TITLE
/fly doesnt not work even when added perm nodes to LP

### ISSUE THREAD

**Issue by Nymorph** [John-Paul-R/Essential-Commands#252]
/fly cmd doesnt not work for players even with ther permission node: Version 1.20.1

**Comment by Nymorph** [comment]
![image](https://github.com/John-Paul-R/Essential-Commands/assets/147357810/a1efb68c-fb9f-4c4b-b7ef-2be9907520f7)

**Comment by John-Paul-R** [comment]
This was caused by a conflict with `ftbessentials`, which provided the same commands and was running on the server at the same time.

Related discord chat: https://discord.com/channels/513219024927326211/857077956336943154/1161429996057936022
