### ISSUE TITLE
Translations not working

### ISSUE THREAD

**Issue by notlin4** [John-Paul-R/Essential-Commands#254]
The translation for the mod is not working in the game. I have tried using different languages, but the text is still in English.

**Comment by John-Paul-R** [comment]
Hi, thanks for the report!

> I have tried using different languages

Can you give an example of a configuration you've used? What actions have you taken?

**Comment by notlin4** [comment]
@John-Paul-R I tried using a language that includes translation (e.g. Chinese), but it didn't work
