### ISSUE TITLE
[1.20.1][Fabric][Mod Compatablity] RightClickHarvest

### ISSUE THREAD

**Issue by WildFyr16** [John-Paul-R/Essential-Commands#258]
When having Essential Commands installed, RightClickHarvest no longer works on our server. Is this a known issue or something I can change to re-enable or would this require an update on the mods end?

**Comment by John-Paul-R** [comment]
That is... surprising. What MC, RightClickHarvest, and EC versions are you using?

**Comment by WildFyr16** [comment]
Oh sorry, thought I marked this as sovled, I accedentally reset all the configs for my mods when I updated my servers mod list (not really sure how) so when RightClickHarvest was not working (I had not tried with a hoe) I thought this mod was somehow interfearing until I also noticed a few other mod not workijg as rhey were before ans found out all of my modified configeration files where reset. RCH works perfect with this mod installed too.

**Comment by John-Paul-R** [comment]
Awesome, glad to hear it's working for you. Thanks for the clarification!
