### ISSUE TITLE
Are there more available tags

### ISSUE THREAD

**Issue by YumesomeZakura** [John-Paul-R/Essential-Commands#260]
Dear author, I installed this mod on my server and noticed that "%player:/displayname%" variable can be used to replace the player name in mtod. I would like to know if there are other variables that can be used, such as displaying the last login IP and time when a player logs in. Where can I obtain these variables? Thanks.

**Comment by John-Paul-R** [comment]
Any of these should work! https://placeholders.pb4.eu/user/default-placeholders/

And, depending on the mods you have installed, these may be available as well: https://placeholders.pb4.eu/user/mod-placeholders/

**Comment by John-Paul-R** [comment]
Closing as resolved, give me a ping if not so!
