### ISSUE TITLE
When creating Taterzens fake player, PlayerDataManager.getByUuid NRE - Player can no longer join

### ISSUE THREAD

**Issue by ShockerAttack01** [John-Paul-R/Essential-Commands#279]
Hello I discovered this recently in 1.20.1 on a server when I had the Taterzens mod installed along side this mod Essential Commands and when I ran the command /npc create (Insert name). It just broke and kicked my player from my server with the output of "Internal Exception: io.netty.handler codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.fiberno.essentialcomnands.playerdata.PlayerData.getPlayerO"
because the return value of "con.fibernc.essentialcommands.playerdata.PlayerDataManager getbyUuid< java.util UUID)" is null"
When I tried to rejoin same output I fixed it by deleting my player data from the server and rejoining but after I tried it through the GUI version of the Taterzens mod it permentally broke my player and I cant join my server currently on that account.

**Comment by John-Paul-R** [comment]
Hm. I cannot reproduce this issue with `/npc create <any_name>`. Versions used:

```
Minecraft 1.20.1
---
essential_commands 0.35.0-mc1.20.1
fabric-api 0.92.2+1.20.1
taterzens 1.11.7
---
Fabric Loader 0.15.11
java 21
```

---

More information may be useful. Can you provide a your `logs/latest.log` file (after the issue occurs), uploaded to site like https://mclo.gs? The current snippets of output don't give much to go on.

**Comment by ShockerAttack01** [comment]
Sadly I don't have the logs because my server for some reason hates recording them at times. I will figure out how to get the logs to work again then I will recreate it for you and send them over.

**Comment by John-Paul-R** [comment]
Got a repro! This currently only happens when `nickname_above_head` is set to `true` in `config/EssentialCommands.properties`.

Will have a fix out in the next release.

**Comment by ShockerAttack01** [comment]
Oh nice I am looking forward to the fix thanks!
Do you still need a log?

**Comment by John-Paul-R** [comment]
> Do you still need a log?

Nope! The log was just to give me information to reproduce the issue. Since I've recreated it, I now have all the information I need. Thanks!

**Comment by John-Paul-R** [comment]
By the way, you can get the dev build from "artifacts" here https://github.com/John-Paul-R/Essential-Commands/actions/runs/9538454801

**Comment by ShockerAttack01** [comment]
Okay, thanks for letting me know that I can get a version of the mod that works with taterzens early.
