### ISSUE TITLE
/back not working

### ISSUE THREAD

**Issue by kerem179** [John-Paul-R/Essential-Commands#303]
whenever i use /back command it says (could not execute command 'back' command. No previous location found.i am using the 1.20.6 version maybe that the problem

**Comment by John-Paul-R** [comment]
What are you trying to go back to?

By default, `/back` only tracks previously teleported-to locations. If you want to go back to a death location, you need to enable `allow_back_on_death` in the config.

**Comment by kerem179** [comment]
thx so much

**Comment by John-Paul-R** [comment]
yw <3

Closing as completed!
