### ISSUE TITLE
Latest version on Modrinth is not set as compatible with 1.21.1

### ISSUE THREAD

**Issue by SusStew** [John-Paul-R/Essential-Commands#304]
Please set version 0.35.2-mc1.21 as compatible with 1.21.1. This version is compatible with 1.21.1 but because it is not set as such on Modrinth, automated mod downloaders do not know this and will not download this version.

**Comment by John-Paul-R** [comment]
good call, ty

**Comment by John-Paul-R** [comment]
done!
