### ISSUE TITLE
Named Entity Death Messages

### ISSUE THREAD

**Issue by Soham52** [John-Paul-R/Essential-Commands#35]
add a gamerule or feature, such that any entity or mob which is named will have a death message like [name] was killed by [cause]
![image](https://user-images.githubusercontent.com/73898737/124882509-1310a300-dfee-11eb-8084-fd9b656b3410.png)

**Comment by John-Paul-R** [comment]
This might be a bit out of scope for EssentialCommands, but should be easy enough to implement as its own, small mod. Might do this in the future as a rainy-day project. Leaving this issue open until I make a proper to-do list to add it to.

**Comment by John-Paul-R** [comment]
Implemented in my new mod, [Server Announce](https://github.com/John-Paul-R/server-announce). (It is currently the mod's only feature :P)
