### ISSUE TITLE
/tpahere command

### ISSUE THREAD

**Issue by MattElekHarris** [John-Paul-R/Essential-Commands#49]
It would be great to have a command to TP players to the player who sent the request, like tpahere, as is common in many other Essentials server plugins and mods.

**Comment by MattElekHarris** [comment]
Wow, that’s awesome! You should add this mod to your featured list on GitHub Sponsors! I’m a student, so it’s not much, but I’d love to be able to support you. Thanks!

**Comment by John-Paul-R** [comment]
Good idea. Thanks for the support!
