### ISSUE TITLE
[Suggestion] Default home-name value

### ISSUE THREAD

**Issue by ginsm** [John-Paul-R/Essential-Commands#62]
I think, given no `home-name` whilst using the `/home` command, the `home-name` should default to using `default` as the name. I think this would compliment #50 very well. It'll also prevent having to type `/home tp <home-name>` when there's a limit of one home per player.

**Comment by John-Paul-R** [comment]
Resolved in `home set` by #205, `home tp` has defaulted to a player's only home for a while now. Closing as completed.
