### ISSUE TITLE
[Suggestion] Disable fly when switching to gamemode survival

### ISSUE THREAD

**Issue by ginsm** [John-Paul-R/Essential-Commands#63]
It feels a bit unnatural to have `fly` enabled when you switch into survival -- especially when you go to use your Elytra unknowingly. Perhaps make this configurable?

**Comment by John-Paul-R** [comment]
I'm quite confused. Why would you ever use `/fly` if not in survival/adventure?

**Comment by ginsm** [comment]
Ah sorry about that, I'll try and clarify a bit better.

Basically what I've experienced is that switching to survival from creative or spectator (on version `0.16.1-mc1.17`) leaves flight enabled for survival.

That behavior caught me off guard; I was expecting flight to be disabled as I hadn't previously enabled it in survival.

**Comment by Soham52** [comment]
Going to confirm that i have been experiencing the same

**Comment by John-Paul-R** [comment]
Oh, that's exceedingly odd. Will look into this.

**Comment by John-Paul-R** [comment]
If all has gone well, this should be fixed by [0.16.2](https://github.com/John-Paul-R/Essential-Commands/releases/tag/0.16.2-mc1.17.1).
