### ISSUE TITLE
[Suggestion] TeleportAsk(Here) suggestions

### ISSUE THREAD

**Issue by ginsm** [John-Paul-R/Essential-Commands#64]
Here's a few suggestions I have for `/tpa` and `/tpahere` (grouping them so I don't completely spam lol):

1. There should be a timeout message when a request expires (for both the issuer and recipient).
2. The TTS narrator currently doesn't narrate `/tpa(here)` request prompts
3. The requests are spammable currently -- maybe make it so people can't issue them again until their last request has timed out?
4. There should be a way to cancel them (`/tpcancel`) -- this would be useful if you need to fly somewhere, otherwise the player may teleport to you mid-air.. (definitely didn't happen, no way :P)
5. `/tpaccept` and `/tpdeny` (and potentially `/tpcancel`) could default to a LIFO basis if no target was provided (i.e. respond to the latest request, and then the second latest, and so forth).

There's also a bug with teleportation that results in the XP level/progress showing up as 0 with inter-dimensional travel.

Thanks for the mod, I hope you don't mind the spam! :joy:

**Comment by John-Paul-R** [comment]
I like most of these. Will look into adding them at some point. Thanks for the clear, concise list.

**Comment by KyGost** [comment]
@ginsm 
> There's also a bug with teleportation that results in the XP level/progress showing up as 0 with inter-dimensional travel.

This is a vanilla bug.
You can install this mod for a fix:
https://modrinth.com/mod/fabriccrossdimtpfix

**Comment by ginsm** [comment]
@KyGost Thanks for the link, I'll check it out :)

**Comment by John-Paul-R** [comment]
Finally got around to adding some of these:
  - "Teleport timeout messages" - added in 4a3b6b39a3cf4af78d64c5251e251ff13900989d
  - `/tpcancel`  - added in 79df750e7bf25b0364909c10b085cb3234080fe2
  - "Disallow `/tpa` spamming" - added in 5ca23b7fd6673943b7c33d131afc2b4dfbb6df9b

Not opposed to adding the others. This is just what is done so far.

**Comment by John-Paul-R** [comment]
Remaining requests:

> The TTS narrator currently doesn't narrate /tpa(here) request prompts

> /tpaccept and /tpdeny (and potentially /tpcancel) could default to a LIFO basis if no target was provided (i.e. respond to the latest request, and then the second latest, and so forth).

**Comment by John-Paul-R** [comment]
Closing this as completed. Have broken out the last 2 tasks into their own Issues: #125, #126
