### ISSUE TITLE
Allow non-ops to set own Nicknames

### ISSUE THREAD

**Issue by maxheyn** [John-Paul-R/Essential-Commands#68]
I'm running a server without any permissions mods. Right now only ops can use /nickname set. I would like to allow my players to be able to set their own nicknames.

**Comment by KyGost** [comment]
This would be nice.
(+1)

**Comment by KyGost** [comment]
Relates: #65

**Comment by John-Paul-R** [comment]
Closing, as progress on this issue will be tracked by #65.
