### ISSUE TITLE
bumb to 21w39a

### ISSUE THREAD

**Issue by PortableGames** [John-Paul-R/Essential-Commands#70]
add support to 21w39a fapi 0.40.5

**Comment by John-Paul-R** [comment]
I do not officially support snapshot versions. Too much changes too quickly. I will support 1.18 when it releases.

(You might be able to get Essential Commands to work by editing the required minecraft and fabric versions in the fabric.mod.json in the jar, but this is not a guarantee. If anything that Essential Commands relies on has changed, this will not work.)
