### ISSUE TITLE
Require ban items command

### ISSUE THREAD

**Issue by 1636578433** [John-Paul-R/Essential-Commands#77]
As you know some mods items are so powerful, they should not allow use on the server.
I hope you can add the command to ban items,it will be useful in fabric server

**Comment by John-Paul-R** [comment]
This request is a bit out of scope for Essential Commands. It is a good idea that I think fit well in a dedicated mod. My goal, for the most part, is to have Essential Commands be a fairly self-contained mod, not really caring about what other mods you have installed.
