### ISSUE TITLE
PlayerRoles requires explicit `/role reload` (permissions are not loaded at server start)

### ISSUE THREAD

**Issue by John-Paul-R** [John-Paul-R/Essential-Commands#78]
>having a weird issue with this and player roles, for some reason, those with the permission to use nicknames lose the permission upon server restart, and can't run the command...
Running ./role reload fixes this, but it's not really efficient to run that command every time the server restarts.
Seems to happen with any essentials command.
https://www.toptal.com/developers/hastebin/yakumosigo.json
Here's the roles.json, only happens with essentials-commands commands for some reason.

- From [Alkia on Discord](https://discord.com/channels/513219024927326211/857077956336943154/904513384978980895)

Me:
> Thanks for the detailed explanation of the problem. I was able to successfully reproduce this issue, but I have absolutely no idea why it is happening. I created an Issue on GitHub so that the problem is tracked. Will fix this when I figure out what is causing this weirdness.

**Comment by pahanakun** [comment]
For some reason Player Roles isn't (completely) loading its config on server start. 

The issue (for me anyways) extends beyond Essential Commands. Any commands given to roles (ie /give which normally requires being op) are not given to players with that role. Any commands that are supposed to be blocked in that role, are accessible until /role reload is executed. Also, Styled Chat does not apply prefixes/coloring/formatting to player names until /role reload is executed.

One thing that Player Roles *does* load from its config on server start is the "command_block" role if used to give command blocks access to all commands. It will load this role, but none of the player roles in the rest of its config. This command_block role is necessary to set up a work-around using command blocks:

https://www.reddit.com/r/MinecraftCommands/comments/rxtzjn/how_to_update_statleavegame_when_server_stops_or/hrlj7pu/

**Comment by John-Paul-R** [comment]
(Potentially?) Related PlayerRoles issue [NucleoidMC/player-roles/#45](https://github.com/NucleoidMC/player-roles/issues/45)

**Comment by John-Paul-R** [comment]
This issue has been fixed by @Gegy as of [PlayerRoles v1.5.1](https://github.com/NucleoidMC/player-roles/releases/tag/v1.5.1)!
