### ISSUE TITLE
/rtp puts players on top of the Nether

### ISSUE THREAD

**Issue by VioletRoses** [John-Paul-R/Essential-Commands#81]
Whenever anyone uses /rtp in the nether, it puts them on top of the nether's ceiling. Tested on 1.18-rc3 and 1.18 full release, otherwise unmodded.

**Comment by John-Paul-R** [comment]
Ah, that actually makes perfect sense considering how I coded it. Good catch!

Will either disable RTP in the nether or come up for a new system for selecting locations when in that world.
