### ISSUE TITLE
Nicknames break Styled Chat displayName overrides

### ISSUE THREAD

**Issue by Patbox** [John-Paul-R/Essential-Commands#83]
Someone reported to me that your mod breaks displayName overrides from my Styled Chat.

It could be resolved by replacing Text variable inside of getDisplayName() mixin instead of returning your own one

**Comment by John-Paul-R** [comment]
Ah, good call, I'd forgotten about this. Will have a fix out within the day. Thanks for looking into this, I appreciate it.
