### ISSUE TITLE
/rtp always teleporting to y=2 with ServerCore

### ISSUE THREAD

**Issue by pahanakun** [John-Paul-R/Essential-Commands#87]
game version 1.18.1

everytime without fail when using /rtp y always = 2

most of the time I'm teleporting into solid blocks. It should be teleporting to the top of the highest block afaik

seems to be some sort of mod imcompatibility, it works fine when its the only mod running alongside fabric-api

mod list: https://pastebin.com/f0CCEjfS

ServerCore appears to be the culprit, as soon as it was enabled I started /rtp -ing to y=2 again
https://www.curseforge.com/minecraft/mc-mods/servercore

**Comment by John-Paul-R** [comment]
Thanks for the detailed report. Will look into this.

**Comment by John-Paul-R** [comment]
Corresponding ServerCore issue: Wesley1808/ServerCore#16

**Comment by John-Paul-R** [comment]
While this was already patched in `ServerCore`, I've also moved away from using world.raycast as of c689a3eb1edb28a007843009b19dfaf3e3e0ab04, so the next version of EC should be compatible with all previous versions of `ServerCore`, as well.
