### ISSUE TITLE
suggestion - add /anvil command

### ISSUE THREAD

**Issue by pahanakun** [John-Paul-R/Essential-Commands#88]
It would be great if we could have an /anvil command to use an indestructible anvil wherever we want.

Other mods that add /enderchest and /workbench do this as well, I'd hate to have to switch from Essential-Commands or have two mods installed that do the same thing.

**Comment by John-Paul-R** [comment]
Resolved by 3393e29fddd2bfdc3fc73fdbe7602d744165ac8b.
