### ISSUE TITLE
Request to have just /home as an alternative to /home tp

### ISSUE THREAD

**Issue by Rozsy** [John-Paul-R/Essential-Commands#92]
Request to have just /home as an alternative to /home tp that sends you to your first home, my server will only ever use 1 home, and this is how my players are used to forges old essentials way of going to home

**Comment by John-Paul-R** [comment]
Thanks for the suggestion! I agree, this would be a useful addition.

This will eventually be implemented as default homes, tracked in #62.

Closing this issue in favor of that one, where work on this enhancement will be tracked.
