### ISSUE TITLE
Command / Teleportation Costs

### ISSUE THREAD

**Issue by taliform** [John-Paul-R/Essential-Commands#93]
Teleport commands at the moment are too powerful, and don't have any balancing features such as adding costs (i.e. experience, levels, items, etc.) in exchange of using commands.

**Comment by John-Paul-R** [comment]
Assigning costs per command sounds like a good idea for a separate mod. This isn't necessarily EC specific. Might create such a mod, as I do not currently know of one that exists, and I like the idea. This particular feature will not be added to EC directly, though.

Will ping you here if/when I make that command costs mod.
