### ISSUE TITLE
Suggestion - RTP Min Radius

### ISSUE THREAD

**Issue by Laifsyn** [John-Paul-R/Essential-Commands#95]
So if you don´t want people having that 0 in a million chance of spawning 1 block away from server spawn

**Comment by IAmNotLiable** [comment]
Also a rtp center option

**Comment by John-Paul-R** [comment]
> 0 in a million chance of spawning 1 block away from server spawn

Er, with the current implementation, it is a literal 0% chance.

RTP destinations are selected the set of points on the perimeter of the circle with radius `RTP_RADIUS`. (not from the set of points within the circle)

The RTP position selection code:
```java
int r = CONFIG.RTP_RADIUS.getValue();
final double angle = (new Random()).nextDouble()*2*Math.PI;
final double delta_x = r * Math.cos(angle);
final double delta_z = r * Math.sin(angle);

// center = sever spawn position
final double new_x = center.pos.x + delta_x;
final double new_z = center.pos.z + delta_z;
```

---

Is this something that you observed? (There were some strange bugs with RTP reported recently. Some have been resolved already. Some I am patching soon. Could be related to one of these if so.)

**Comment by John-Paul-R** [comment]
> Also a rtp center option

Doable. Will add this soon. Tracking in #96

**Comment by John-Paul-R** [comment]
Closing, as this should already be effectively implemented. Feel free to reopen if issues relating to this arise.
