### ISSUE TITLE
No "enable-grindstone" config option

### ISSUE THREAD

**Issue by solitary-sails** [John-Paul-R/Essential-Commands#98]
There is no "enable-grindstone" option in the config file.I tried to add it manually but it doesn't work.Now I can't disable it.

**Comment by John-Paul-R** [comment]
Right now, it and stonecutter both share the same perms as workbench. If a dedicated perm would be useful to you, just lmk and I can add it

**Comment by solitary-sails** [comment]
I think it's useful. I don't think the portable GUI should be unlocked until the player has the ability to mass produce these blocks. I'd appreciate it if you could add dedicated perms back.

**Comment by John-Paul-R** [comment]
Resolved by c6e6db2d8c363a7e7f5f80132612e7c18726b161

Just need to figure out how I want to handle existing permissions changing before I release...
